<?php

function njs_company_testimonials_menu() {
  $items = array();
  $items['user/%/approve-testimonial'] = array(
    'page callback'   => 'njs_approve_testimonial_page',
    'access callback' => TRUE,
    'type'            => MENU_CALLBACK,
  );
  $items['user/%/unapprove-testimonial'] = array(
    'page callback'   => 'njs_approve_testimonial_page',
    'access callback' => TRUE,
    'type'            => MENU_CALLBACK,
  );
  $items['user/%/delete-testimonial'] = array(
    'page callback'   => 'njs_delete_testimonial_page',
    'access callback' => TRUE,
    'type'            => MENU_CALLBACK,
  );
  return $items;
}

function njs_approve_testimonial_page() {
  $output .= '<p>Click "Show on Profile" below to make this testimonial show up on your profile as public content.</p>';
  $output .= drupal_get_form('njs_approve_testimonial_form');
  return $output;
}

function njs_unapprove_testimonial_page() {
  $output .= '<p>Click "Hide from Profile" below to avoid this testimonial showing up on your public profile.</p>';
  $output .= drupal_get_form('njs_unapprove_testimonial_form');
  return $output;
}

function njs_delete_testimonial_page() {
  $output .= '<p>Are you sure you want to delete this testimonial? Once you have deleted it is deleted forever and cannot be retreved in future.</p>';
  $output .= drupal_get_form('njs_delete_testimonial_form');
  return $output;
}


function njs_approve_testimonial_form() {
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Show on Profile'),
  );
  $form['cancel'] = array(
    '#type' => 'button',
    '#attributes' => array('onClick' => 'location.replace("'. referer_uri() .'"); return false;'),
    '#value' => t('Cancel'),
  );
  return $form;
}

function njs_unapprove_testimonial_form() {
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Show on Profile'),
  );
  $form['cancel'] = array(
    '#type' => 'button',
    '#attributes' => array('onClick' => 'location.replace("'. referer_uri() .'"); return false;'),
    '#value' => t('Cancel'),
  );
  return $form;
}

function njs_delete_testimonial_form() {
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Delete Testimonial'),
  );
  $form['cancel'] = array(
    '#type' => 'button',
    '#attributes' => array('onClick' => 'location.replace("'. referer_uri .'"); return false;'),
    '#value' => t('Cancel'),
  );
  return $form;
}

function njs_approve_testimonial_form_submit($form_id, $form_values) {
  $n = node_load(array( 'nid' => arg(3) ));
  $n->field_testimonial_approved[0][value] = 'approved';
  node_save($n);
  drupal_set_message('Testimonial has been set public');
  drupal_goto('user/'. arg(1) .'/admin');
}

function njs_unapprove_testimonial_form_submit($form_id, $form_values) {
  $n = node_load(array( 'nid' => arg(3) ));
  $n->field_testimonial_approved[0][value] = 'not-approved';
  node_save($n);
  drupal_set_message('Testimonial has been set public');
  drupal_goto('user/'. arg(1) .'/admin');
}

function njs_delete_testimonial_form_submit($form_id, $form_values) {
  node_delete(arg(3));
  drupal_set_message('Testimonial has been deleted');
  drupal_goto('user/'. arg(1) .'/admin');
}

?>
